# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(max_length=50),
        ),
    ]
